// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VSIXProject4
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidVSIXProject4PackageString = "51b91bcc-a22a-4efd-a699-47b3e68f5923";
        public static Guid guidVSIXProject4Package = new Guid(guidVSIXProject4PackageString);

        public const string CustomContextString = "b45c8ed5-456d-4eaf-9bd8-aff6e3c6881a";
        public static Guid CustomContext = new Guid(CustomContextString);

        public const string guidVSIXProject4PackageCmdSetString = "b6d9ba2c-139e-43d1-9a8e-60abb2137aa6";
        public static Guid guidVSIXProject4PackageCmdSet = new Guid(guidVSIXProject4PackageCmdSetString);

        public const string guidImagesString = "ea057b5d-8db0-461e-b1f3-dcac5d45bdc1";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int ToolWindow1CommandId = 0x0100;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}